[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
ensure_newline_before_comments = true
src_paths = ["app","data","stage1","stage2","stage3","UI","QDE","utils","monitoring","config","test"]
known_first_party = ["app","data","stage1","stage2","stage3","UI","QDE","utils","monitoring","config"]



[tool.mypy]
python_version = "3.11"
strict_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_optional = true
pretty = true

[[tool.mypy.overrides]]
module = "pandas.*"
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = "scipy.*"
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = "redis.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "redis.asyncio.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "lz4.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "aiohttp.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "prometheus_client.*"
ignore_missing_imports = true
